### ISSUE TITLE
Reset password link doesnt work!

### ISSUE THREAD

**Issue by Madgutts** [schemen/monsterforge#12]
Hi there, i have forgotten my password by all accounts and for some reason my password isnt in my password manager!
So i clicked the forgot password link, which emailed me a code, however the link doesnt work...
It doesnt seem to be a Web link!
http://monsterforge:8080/accounts/reset/MzAyMw/5lb-d6b986481967a8a33501/

**Comment by schemen** [comment]
Sorry, I didn't get a notification about that!

Hm I see the error, when you request a new link, replace the URL with 

http://monsterforge:8080 -> https://forge.dndbox.com

In the meanwhile I'll see if I can fix it!

**Comment by schemen** [comment]
Tested the fix on the development instance successfully. It is now deployed on the live instance!

Thanks for reporting this, I will close this issue then.
