### ISSUE TITLE
The height of the minis can be dynamically adjusted?

### ISSUE THREAD

**Issue by esiefker** [schemen/monsterforge#6]
I'm giving monsterforge small creatures, with images of varying height.  I do not have "Use fixed height" clicked.  I still get minis of the same height.  Example output attached. 

![sheet_1](https://user-images.githubusercontent.com/25390776/74581108-16c30600-4f71-11ea-8a6c-8004b301b9e3.png)

**Comment by schemen** [comment]
The descision was that Tiny, Small and Medium creatures have the same base size as it would be almost unrecognisable when printing. 

This is still part of the code that I am trying to understand but this is as it currently is :)

**Comment by schemen** [comment]
https://github.com/schemen/monsterforge/commit/b39eaab36ec89b209546aaf45b8f75827a1fa155

Here I allow small size to be printed. Have a look at https://imgur.com/xIxKDGD

I am not certain if this is good, the print itself is very small and barely recognizable once on paper.

**Comment by esiefker** [comment]
Thanks for looking at this.  I think the base size is fine, but what about the height?  Can we get an option to get the fold line at the top of the image, wherever that may be? 

![example](https://user-images.githubusercontent.com/25390776/75078434-31deca00-54cb-11ea-93fa-1a4108474f0f.png)

**Comment by schemen** [comment]
Hm... I'll check and let you know!

**Comment by schemen** [comment]
Well it has been a while, but it has been done with #73, It should all work cleanly now and even improved!
