### ISSUE TITLE
Wrong dimensions for A4 format 

### ISSUE THREAD

**Issue by nesges** [schemen/monsterforge#81]
I just generated some minis (https://forge.dice.quest/bestiary/5030) to paper format A4 and the resulting document is 716.1 x 1019.5 mm large

![AcroRd32_2022-08-02_22-01-57](https://user-images.githubusercontent.com/1583898/182462923-363803a8-460c-4d92-bca8-9c42d48870d8.png)

![chrome_2022-08-02_22-02-33](https://user-images.githubusercontent.com/1583898/182463004-14688a67-c98b-4877-ba1d-757938f04895.png)

**Comment by schemen** [comment]
That is very interesting! While the ratio is A4 (You "force" print it to A4) is correct and all measures up, the actual PDF is gigantic. 

Thank you for reporting the issue, I'll have a look!
