### ISSUE TITLE
Feature Request: Rectangular Bases

### ISSUE THREAD

**Issue by Joakker** [schemen/monsterforge#84]
First of all, thank you for the awesome tool. I know this is primarily intended for use with D&D, but it's also very useful in the context of Wargames. However, for certain units, it would be very useful to be able to give them rectangular bases, for example 1"x2", for things like cavalry or beasts.
Thank you once again

**Comment by schemen** [comment]
Hey!

Thank you for the praise :)

Could you expand a bit? Since this mostly fro TTRPG games using grids, how is wargaming done? Also on 1 inch grid? Could you explain?

**Comment by Joakker** [comment]
Most wargames don't seem to use a grid system, instead preferring to measure movement in real world distance (6", 12", that sort of stuff). Things like infantry and creatures like giants, spiders and the like can be mounted on square/round bases, but for things that are longer than they're wide, like in the image below, you need rectangle/oval bases. Here you can see a unit of cavalrymen mounted on such bases.

![image](https://user-images.githubusercontent.com/51842726/184948074-ebc38d7d-8e3e-49a3-9f6e-002c4b420536.png)

My suggestion would be to make a toggle saying something like `cavalry`, that would make a base of X by X, print like a base of  X by X/2. Something like this (Done with MonsterForge and adjusted for the correct size)

![image](https://user-images.githubusercontent.com/51842726/184949528-bb472100-0c3b-41df-8676-139834291083.png)

**Comment by schemen** [comment]
Hey thanks for the description! I think I may be able to create an option like that, I like to help the war gaming community!
I'll have to think about implementation and my time :) I'll check and it may not even be that big of a thing :+1:

**Comment by Joakker** [comment]
Thank you so much! 😄

**Comment by schemen** [comment]
@Joakker Please have a look at https://forge-dev.dice.quest/quickbuild/ - this is the dev site. I've added the option to the quickbuilder. Please let me know what you think.

**Comment by Joakker** [comment]
Yeah, this is exactly what I was thinking. Thank you so much

**Comment by schemen** [comment]
It's merged now and released on the main server!
Feel free to share it with your wargaming friends :)
