### ISSUE TITLE
Problem to generate minis

### ISSUE THREAD

**Issue by FrankyAC** [schemen/monsterforge#90]
Hi ive problems to generate minis the error msg 
![image](https://user-images.githubusercontent.com/43166789/209388329-bb072912-925f-42a7-a0d4-2d1605c33c48.png)

![image](https://user-images.githubusercontent.com/43166789/209388433-a9af8efd-8119-493e-8dfe-a7edf15b5afe.png)

**Comment by schemen** [comment]
Hi, Thank you for reporting this bug. Could you please send me the ID of your Bestiary to TbsywnrFBAjm.k5YIaQh4nYxh@privacyrelay.ch ? I will check the logs as well as the bestiary to see if I can find what is happening!

**Comment by schemen** [comment]
Thanks for the mail, I see some general errors! I'll see what I can do and come back to you

**Comment by schemen** [comment]
Alright, the fix is live on the servers, could you please try again?

**Comment by FrankyAC** [comment]
Yeah! I've tried it works perfectly!!!

Thank you so much, you saved my xmas dnd session!!!

Have nice holidays and happy new year, your dnd tools rocks!!!

Greetings!!

**Comment by schemen** [comment]
Perfect, I'll close this issue then :) 
Thank you for the kind words!
Marry Xmas and happy new year!
